---
info:
  title: kafdrop
  description: Kafdrop is a web UI for viewing Kafka topics and browsing consumer groups
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/kafdrop
  x-cortex-tag: kafdrop
  x-cortex-type: service
  x-cortex-domain-parents:
    - tag: data-platform-transport
  x-cortex-groups:
    - exposure:opensource
openapi: 3.0.0
servers:
  - url: "/"
