// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/person.proto

package kafdrop.protos;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kafdrop.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>.kafdrop.Person.Contact contact = 4;</code>
   * @return The enum numeric value on the wire for contact.
   */
  int getContactValue();
  /**
   * <code>.kafdrop.Person.Contact contact = 4;</code>
   * @return The contact.
   */
  kafdrop.protos.Person.Contact getContact();

  /**
   * <code>repeated string data = 5;</code>
   * @return A list containing the data.
   */
  java.util.List<java.lang.String>
      getDataList();
  /**
   * <code>repeated string data = 5;</code>
   * @return The count of data.
   */
  int getDataCount();
  /**
   * <code>repeated string data = 5;</code>
   * @param index The index of the element to return.
   * @return The data at the given index.
   */
  java.lang.String getData(int index);
  /**
   * <code>repeated string data = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the data at the given index.
   */
  com.google.protobuf.ByteString
      getDataBytes(int index);
}
